TrajectoryPlannerROS:
  max_vel_x: 0.6
  min_vel_x: 0.01
  max_vel_theta: 1.5
  min_in_place_vel_theta: 0.01

  yaw_goal_tolerance: 0.5
  xy_goal_tolerance:  0.4

  acc_lim_theta: 0.4
  acc_lim_x: 0.2
  acc_lim_y: 0.2


  holonomic_robot: false
